// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeminjamRuangAPI.Data;

#nullable disable

namespace PeminjamRuangAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PeminjamRuangAPI.Entities.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Menunggu");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TanggalSelesai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tujuan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peminjaman");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 31, 16, 483, DateTimeKind.Local).AddTicks(4319),
                            IsDeleted = false,
                            NamaPeminjam = "Budi Santoso",
                            Ruangan = "Ruang 101",
                            Status = "Disetujui",
                            TanggalPinjam = new DateTime(2026, 2, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Tujuan = "Rapat Tim"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 31, 16, 483, DateTimeKind.Local).AddTicks(4338),
                            IsDeleted = false,
                            NamaPeminjam = "Siti Aminah",
                            Ruangan = "Lab Komputer",
                            Status = "Menunggu",
                            TanggalPinjam = new DateTime(2026, 2, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Tujuan = "Praktikum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
